export const exampleData = {
  adult: false,
  also_known_as: [
    "劉亦菲",
    "Liu Yi Fei",
    "Yi-Fei Liu",
    "Liu Yi-Fei",
    "Crystal Liu",
    "刘亦菲",
    "An Feng",
    "Liu Ximeizi",
    "刘茜美子",
    "安风",
    "유역비",
    "Γιφέι Λιου",
    "Lưu Diệc Phi",
    "류이페이",
  ],
  biography:
    "Liu Yifei ( born An Feng; August 25, 1987) is a popular Chinese-American actress, model and singer. She was born in China and moved to the United States when she was 11.",
  birthday: "1987-08-25",
  deathday: null,
  gender: 1,
  homepage: null,
  id: 122503,
  imdb_id: "nm1703577",
  known_for_department: "Acting",
  name: "Liu Yifei",
  place_of_birth: "Wuhan, Hubei, China",
  popularity: 7.764,
  profile_path: "/cL6JccAYqiZQEAIEFObEUC9LTt7.jpg",
};
