export const exampleMovieCredits = {
  cast: [
    {
      adult: false,
      backdrop_path: "/2OQkSOyC5HuCNpq0XO5EEPEdazX.jpg",
      genre_ids: [35, 10751],
      id: 10022,
      original_language: "en",
      original_title: "The Pacifier",
      overview:
        "Navy SEAL Shane Wolfe is handed a new assignment: Protect the five Plummer kids from enemies of their recently deceased father -- a government scientist whose top-secret experiment remains hidden in the kids' house.",
      poster_path: "/brkyQKNcaVNWGsCBCW5bKy9zVeW.jpg",
      release_date: "2005-03-04",
      title: "The Pacifier",
      video: false,
      vote_average: 6,
      vote_count: 2375,
      popularity: 28.368,
      character: "Shane Wolf",
      credit_id: "52fe43099251416c7500111b",
      order: 0,
    },
    {
      title: "Pitch Black",
      genre_ids: [53, 878, 28],
      original_language: "en",
      original_title: "Pitch Black",
      poster_path: "/qSv4ZCKmpo3Nqkh7YTvLruE9KcW.jpg",
      video: false,
      vote_average: 6.8,
      overview:
        "When their ship crash-lands on a remote planet, the marooned passengers soon learn that escaped convict Riddick isn't the only thing they have to fear. Deadly creatures lurk in the shadows, waiting to attack in the dark, and the planet is rapidly plunging into the utter blackness of a total eclipse. With the body count rising, the doomed survivors are forced to turn to Riddick with his eerie eyes to guide them through the darkness to safety. With time running out, there's only one rule: Stay in the light.",
      release_date: "2000-02-18",
      vote_count: 3405,
      id: 2787,
      adult: false,
      backdrop_path: "/38Y65sf9O4zLq6Ke2KdpANYk0G3.jpg",
      popularity: 15.734,
      character: "Richard B. Riddick",
      credit_id: "52fe436dc3a36847f80535fd",
      order: 0,
    },
    {
      original_title: "The Chronicles of Riddick",
      poster_path: "/iSaB7jBgsU6sXqKneZpdeRw5MSV.jpg",
      video: false,
      vote_average: 6.5,
      title: "The Chronicles of Riddick",
      overview:
        "After years of outrunning ruthless bounty hunters, escaped convict Riddick suddenly finds himself caught between opposing forces in a fight for the future of the human race. Now, waging incredible battles on fantastic and deadly worlds, this lone, reluctant hero will emerge as humanity's champion - and the last hope for a universe on the edge of annihilation.",
      release_date: "2004-06-11",
      id: 2789,
      adult: false,
      backdrop_path: "/9o0WHLPvHHAznN0H3pBfjjiFioN.jpg",
      genre_ids: [28, 878],
      vote_count: 3073,
      original_language: "en",
      popularity: 13.203,
      character: "Riddick",
      credit_id: "52fe436dc3a36847f805374d",
      order: 0,
    },
    {
      overview:
        'After their narrow escape at the end of "Pitch Black,"  Riddick, Jack and the Imam find themselves at the mercy of a madwoman who intends to entomb Riddick forever as part of a twisted art exhibit.  With little but a shiv and Riddick\'s innate viciousness to aid them, Riddick and his allies must find a way to escape from their captor and her band of mercenaries.',
      id: 2791,
      adult: false,
      backdrop_path: "/3bIMWW8glcaYcKvSVRa1PHe31YV.jpg",
      genre_ids: [28, 16, 878, 53],
      vote_count: 240,
      original_language: "en",
      original_title: "The Chronicles of Riddick: Dark Fury",
      poster_path: "/rfNOl21lDRyqTeORYp4PiBlsW1t.jpg",
      title: "The Chronicles of Riddick: Dark Fury",
      video: false,
      vote_average: 6.1,
      release_date: "2004-06-15",
      popularity: 2.155,
      character: "Richard B. Riddick (Voice)",
      credit_id: "52fe436dc3a36847f8053867",
      order: 0,
    },
    {
      original_language: "en",
      original_title: "xXx",
      poster_path: "/86BnliVDBo2TjKmrgQTJIPHxAKd.jpg",
      video: false,
      vote_average: 5.9,
      title: "xXx",
      overview:
        'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
      release_date: "2002-08-09",
      vote_count: 3245,
      adult: false,
      backdrop_path: "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
      id: 7451,
      genre_ids: [28, 12, 53],
      popularity: 22.153,
      character: "Xander Cage",
      credit_id: "52fe447ec3a36847f8099509",
      order: 0,
    },
    {
      id: 8409,
      adult: false,
      backdrop_path: "/tQVJJ2kODGU0N7UnyPauv0qk8ag.jpg",
      genre_ids: [28, 18],
      original_language: "en",
      original_title: "A Man Apart",
      poster_path: "/z0JUBNk4BTBmeMOudrRH9GnOmK0.jpg",
      video: false,
      vote_average: 6.1,
      vote_count: 648,
      overview:
        "When Vetter's wife is killed in a botched hit organized by Diablo, he seeks revenge against those responsible. But in the process, Vetter and Hicks have to fight their way up the chain to get to Diablo but it's easier said than done when all Vetter can focus on is revenge.",
      release_date: "2003-04-04",
      title: "A Man Apart",
      popularity: 13.818,
      character: "Sean Vetter",
      credit_id: "52fe44a5c3a36847f80a216f",
      order: 0,
    },
    {
      id: 9381,
      adult: false,
      backdrop_path: "/wVTvfxz53pDqrIvbrxhVdKcLhip.jpg",
      genre_ids: [28, 12, 878, 53],
      original_language: "en",
      original_title: "Babylon A.D.",
      poster_path: "/kt9nqD0uOar8IVE9191HXhWOXKI.jpg",
      vote_count: 1544,
      title: "Babylon A.D.",
      vote_average: 5.6,
      video: false,
      overview:
        "A veteran-turned-mercenary  is hired to take a young woman with a secret from post-apocalyptic Eastern Europe to New York City.",
      release_date: "2008-08-20",
      popularity: 17.064,
      character: "Toorop",
      credit_id: "52fe44f0c3a36847f80b2e6f",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/4aAmGZrR15CnVU0VjVuzMHNQ2eZ.jpg",
      genre_ids: [18, 80],
      id: 9950,
      original_language: "en",
      original_title: "Find Me Guilty",
      overview:
        "Based on the true story of Jack DiNorscio, a mobster who defended himself in court for what would be the longest mafia trial in U.S. history.",
      poster_path: "/8M0dkX7jOor7exKor1txoUl9Ynu.jpg",
      release_date: "2006-03-16",
      title: "Find Me Guilty",
      video: false,
      vote_average: 6.6,
      vote_count: 344,
      popularity: 9.493,
      character: "Jackie DiNorscio",
      credit_id: "52fe454ec3a36847f80c6d8f",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/3ZiM6gm2XL8qnhZCXsTjixvaH4v.jpg",
      genre_ids: [28, 80, 18, 53],
      id: 13804,
      original_language: "en",
      original_title: "Fast & Furious",
      overview:
        "When a crime brings them back to L.A., fugitive ex-con Dom Toretto reignites his feud with agent Brian O'Conner. But as they are forced to confront a shared enemy, Dom and Brian must give in to an uncertain new trust if they hope to outmaneuver him. And the two men will find the best way to get revenge: push the limits of what's possible behind the wheel.",
      poster_path: "/fjGCa4oLvgpMVF2jawbjXBWp91v.jpg",
      release_date: "2009-04-02",
      title: "Fast & Furious",
      video: false,
      vote_average: 6.7,
      vote_count: 5529,
      popularity: 13.632,
      character: "Dominic Toretto",
      credit_id: "52fe45a29251416c7505d387",
      order: 0,
    },
    {
      id: 15803,
      video: false,
      vote_count: 16,
      vote_average: 6.6,
      title: "Multi-Facial",
      release_date: "1995-01-01",
      original_language: "en",
      original_title: "Multi-Facial",
      genre_ids: [18],
      backdrop_path: null,
      adult: false,
      overview:
        "Through a series of auditions, a young actor in New York City struggles with his identity.",
      poster_path: null,
      popularity: 1.74,
      character: "Mike",
      credit_id: "52fe467f9251416c7507a1f5",
      order: 0,
    },
    {
      vote_count: 4524,
      id: 47971,
      video: false,
      overview:
        "Extreme athlete turned government operative Xander Cage comes out of self-imposed exile, thought to be long dead, and is set on a collision course with deadly alpha warrior Xiang and his team in a race to recover a sinister and seemingly unstoppable weapon known as Pandora's Box. Recruiting an all-new group of thrill-seeking cohorts, Xander finds himself enmeshed in a deadly conspiracy that points to collusion at the highest levels of world governments.",
      release_date: "2017-01-13",
      backdrop_path: "/7KAXYsemH14agl4ohhNeIxwWXhj.jpg",
      original_language: "en",
      adult: false,
      poster_path: "/hba8zREJpP1AYhaXgb2oJLQeO0K.jpg",
      original_title: "xXx: Return of Xander Cage",
      genre_ids: [28, 12, 80],
      vote_average: 5.9,
      title: "xXx: Return of Xander Cage",
      popularity: 70.919,
      character: "Xander Cage",
      credit_id: "52fe4751c3a36847f812f0f1",
      order: 0,
    },
    {
      overview:
        "Rick (Diesel) is frustrated by the repetitious grind of one-night stands and aimless hustling. Whilst looking for more to his life he meets Heather (Lanza), a neighbour. Rick takes the opportunity to escape his boring life style with her, but soon finds that his volatile behaviour threatens to finish their relationship before it even really begins.",
      release_date: "1997-01-18",
      adult: false,
      backdrop_path: null,
      id: 19083,
      genre_ids: [18],
      vote_count: 24,
      original_language: "en",
      original_title: "Strays",
      poster_path: "/mF6LBmWNAy9LSzy9JWF4IBYOy1l.jpg",
      video: false,
      title: "Strays",
      vote_average: 5.1,
      popularity: 2.87,
      character: "Rick",
      credit_id: "52fe47b89251416c750a347d",
      order: 0,
    },
    {
      overview:
        "Former cop Brian O'Conner partners with ex-con Dom Toretto on the opposite side of the law. Since Brian and Mia Toretto broke Dom out of custody, they've blown across many borders to elude authorities. Now backed into a corner in Rio de Janeiro, they must pull one last job in order to gain their freedom.",
      release_date: "2011-04-20",
      adult: false,
      backdrop_path: "/lvSxooYCRuF3S2kHWXYTrcOtYco.jpg",
      id: 51497,
      genre_ids: [28, 53, 80],
      original_language: "en",
      original_title: "Fast Five",
      poster_path: "/vDztZS30sheoqnJnKyO4QMnf3f8.jpg",
      vote_count: 6231,
      video: false,
      vote_average: 7.3,
      title: "Fast Five",
      popularity: 10.517,
      character: "Dominic Toretto",
      credit_id: "52fe47f6c3a36847f8151abb",
      order: 0,
    },
    {
      id: 82992,
      adult: false,
      backdrop_path: "/mRfI3y2oAd7ejur2di09xC9niqp.jpg",
      genre_ids: [28, 53, 80],
      original_language: "en",
      original_title: "Fast & Furious 6",
      poster_path: "/n31VRDodbaZxkrZmmzyYSFNVpW5.jpg",
      vote_count: 8823,
      video: false,
      vote_average: 6.8,
      title: "Fast & Furious 6",
      overview:
        "Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets convoluted also facing his presumed deceased girlfriend, Letty.",
      release_date: "2013-05-21",
      popularity: 9.604,
      character: "Dominic Toretto",
      credit_id: "52fe48829251416c9108f00b",
      order: 0,
    },
    {
      genre_ids: [878, 28, 53],
      original_language: "en",
      original_title: "Riddick",
      poster_path: "/xhdDd6Gd6EaPBwNdCjNW2HCnIQY.jpg",
      video: false,
      vote_average: 6.3,
      vote_count: 3222,
      overview:
        "Betrayed by his own kind and left for dead on a desolate planet, Riddick fights for survival against alien predators and becomes more powerful and dangerous than ever before. Soon bounty hunters from throughout the galaxy descend on Riddick only to find themselves pawns in his greater scheme for revenge. With his enemies right where he wants them, Riddick unleashes a vicious attack of vengeance before returning to his home planet of Furya to save it from destruction.",
      release_date: "2013-09-02",
      title: "Riddick",
      id: 87421,
      adult: false,
      backdrop_path: "/naGU49u4BXynQ1o5L755pfs8dom.jpg",
      popularity: 24.358,
      character: "Riddick",
      credit_id: "52fe49c39251416c910b810b",
      order: 0,
    },
    {
      id: 211449,
      video: false,
      vote_count: 63,
      vote_average: 6.7,
      title: "Riddick: Blindsided",
      release_date: "2013-07-26",
      original_language: "en",
      original_title: "Riddick: Blindsided",
      genre_ids: [28, 16, 878],
      backdrop_path: null,
      adult: false,
      overview:
        "This motion comic gaps the bridge between 2004's The Chronicles of Riddick, and 2013's Riddick. A new attempt on Lord Marshal Riddick's life is made on the Necromongers' ship. It's time for Riddick to end the years long meandering through space and go back to his roots.",
      poster_path: "/AiWr89Y4g6gkJ3WhVv1TrcSTFMf.jpg",
      popularity: 1.461,
      character: "Riddick",
      credit_id: "52fe4d95c3a368484e1f12e1",
      order: 0,
    },
    {
      original_language: "en",
      original_title: "Los Bandoleros",
      poster_path: "/rqWRTgjHcmcmeRXE1w1LyYZupwS.jpg",
      video: false,
      vote_average: 6.4,
      overview:
        "The film tells the back story about the characters and events leading up to the explosive oil truck heist in Fast &amp; Furious.",
      release_date: "2009-07-28",
      id: 253835,
      title: "Los Bandoleros",
      adult: false,
      backdrop_path: "/uijC23zReJLR3xUq3xh41NuI6vG.jpg",
      genre_ids: [28, 18],
      vote_count: 264,
      popularity: 0.692,
      character: "Dominic Toretto",
      credit_id: "52fe4e959251416c91136967",
      order: 0,
    },
    {
      video: false,
      vote_average: 6.1,
      overview:
        'A policeman is assigned by his superior officer to find and apprehend escaped convict Richard B. Riddick. Riddick was being transported onboard space transport vessel "Hunter-Gratzner", where a bounty hunter who captured him was escorting him to the penal colony "Slam City" and claim the bounty on his head. On its way, the "Hunter-Gratzner" was struck by a meteor shower and crashed on a desert planet.  A female bounty hunter hired by the the persuing policeman begins to suspect there is something more behind the "Hunter-Gratzner" incident.',
      release_date: "2000-01-30",
      vote_count: 32,
      adult: false,
      backdrop_path: null,
      title: "Into Pitch Black",
      genre_ids: [28, 878, 80, 10770],
      id: 244839,
      original_language: "en",
      original_title: "Into Pitch Black",
      poster_path: "/daB2WDVkOXzaWohtuxvOArpRF4X.jpg",
      popularity: 2.959,
      character: "Richard B. Riddick",
      credit_id: "52fe4ef8c3a36847f82b43cd",
      order: 0,
    },
    {
      id: 168259,
      vote_average: 7.3,
      overview:
        "Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
      release_date: "2015-04-01",
      adult: false,
      backdrop_path: "/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg",
      vote_count: 8589,
      genre_ids: [28, 53, 80, 12],
      video: false,
      original_language: "en",
      original_title: "Furious 7",
      poster_path: "/wurKlC3VKUgcfsn0K51MJYEleS2.jpg",
      title: "Furious 7",
      popularity: 115.257,
      character: "Dominic Toretto",
      credit_id: "5431dfd10e0a265915002c34",
      order: 0,
    },
    {
      id: 274854,
      adult: false,
      backdrop_path: "/g8DUZrgCfXRJ5CazfZ5X7qCWcvZ.jpg",
      genre_ids: [14, 28, 12, 878],
      original_language: "en",
      original_title: "The Last Witch Hunter",
      poster_path: "/qXvOpA2nhK5HQ6I95sN3nnMtfjH.jpg",
      vote_count: 2935,
      title: "The Last Witch Hunter",
      vote_average: 5.9,
      video: false,
      overview:
        "The modern world holds many secrets, but by far the most astounding is that witches still live among us; vicious supernatural creatures intent on unleashing the Black Death upon the world and putting an end to the human race once and for all. Armies of witch hunters have battled this unnatural enemy for centuries, including Kaulder, a valiant warrior who many years ago slayed the all-powerful Witch Queen, decimating her followers in the process. In the moments right before her death, the Queen cursed Kaulder with immortality, forever separating him from his beloved wife and daughter. Today, Kaulder is the last living hunter who has spent his immortal life tracking down rogue witches, all the while yearning for his long-lost family.",
      release_date: "2015-10-21",
      popularity: 43.449,
      character: "Kaulder",
      credit_id: "544dff5d0e0a2608d4003f9d",
      order: 0,
    },
    {
      release_date: "2021-05-19",
      adult: false,
      backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
      genre_ids: [28, 80, 53],
      vote_count: 2685,
      original_language: "en",
      original_title: "F9",
      poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
      title: "F9",
      video: false,
      vote_average: 7.7,
      id: 385128,
      overview:
        "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
      popularity: 3309.679,
      character: "Dominic Toretto",
      credit_id: "58433f95c3a3684813001d9f",
      order: 0,
    },
    {
      original_title: "Fast & Furious 10",
      poster_path: "/2DyEk84XnbJEdPlGF43crxfdtHH.jpg",
      video: false,
      overview: "The tenth installment in the Fast Saga.",
      vote_count: 0,
      adult: false,
      vote_average: 0,
      backdrop_path: null,
      title: "Fast & Furious 10",
      genre_ids: [28, 80],
      id: 385687,
      original_language: "en",
      popularity: 226.491,
      character: "Dominic Toretto",
      credit_id: "56d8c1e0c3a3681e3601fdc6",
      order: 0,
    },
    {
      id: 208449,
      video: true,
      vote_count: 16,
      vote_average: 5.3,
      title: "The Final Chapter: The Death of Xander Cage",
      release_date: "2005-04-13",
      original_language: "en",
      original_title: "The Final Chapter: The Death of Xander Cage",
      genre_ids: [28],
      backdrop_path: null,
      adult: false,
      overview:
        "Short filling the gaps between xXx and xXx: State of the Union. Likely rendered non-canon by the release of xXx: Return of Xander Cage (2017). An extra from xXx (2002) Directors Cut.",
      poster_path: "/jomX2BSJHvuKRMzYJPSIb8MC5rP.jpg",
      popularity: 5.45,
      character: "Xander Cage (voice / archive)",
      credit_id: "58f2aae49251413d84004e37",
      order: 0,
    },
    {
      video: false,
      vote_average: 6.9,
      overview:
        "When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.",
      release_date: "2017-04-12",
      adult: false,
      backdrop_path: "/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg",
      vote_count: 8440,
      genre_ids: [28, 80, 53],
      id: 337339,
      original_language: "en",
      original_title: "The Fate of the Furious",
      poster_path: "/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg",
      title: "The Fate of the Furious",
      popularity: 156.067,
      character: "Dominic Toretto",
      credit_id: "5ceab3dc9251414398b96e7a",
      order: 0,
    },
    {
      original_title: "Bloodshot",
      id: 338762,
      video: false,
      vote_average: 6.9,
      overview:
        "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
      release_date: "2020-03-05",
      title: "Bloodshot",
      adult: false,
      backdrop_path: "/zlqMASc3vEtdym2OvXgE7fC6onT.jpg",
      vote_count: 3934,
      genre_ids: [28, 878],
      poster_path: "/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg",
      original_language: "en",
      popularity: 338.78,
      character: "Ray Garrison / Bloodshot",
      credit_id: "5e85b6905294e700154a9a7c",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/jY9ef5nqY4xIIMu3yzW3qamUCoi.jpg",
      genre_ids: [28, 80, 53],
      vote_count: 7595,
      original_language: "en",
      id: 9799,
      poster_path: "/gqY0ITBgT7A82poL9jv851qdnIb.jpg",
      title: "The Fast and the Furious",
      video: false,
      vote_average: 6.9,
      original_title: "The Fast and the Furious",
      overview:
        "Dominic Toretto is a Los Angeles street racer suspected of masterminding a series of big-rig hijackings. When undercover cop Brian O'Conner infiltrates Toretto's iconoclastic crew, he falls for Toretto's sister and must choose a side: the gang or the LAPD.",
      release_date: "2001-06-22",
      popularity: 6.407,
      character: "Dominic Toretto",
      credit_id: "52fe452fc3a36847f80c101f",
      order: 1,
    },
    {
      title: "Boiler Room",
      original_language: "en",
      original_title: "Boiler Room",
      poster_path: "/uYbkko9u3RUbrFO7oDCScxdOlvQ.jpg",
      video: false,
      vote_average: 6.7,
      overview:
        "A college dropout gets a job as a broker for a suburban investment firm and is on the fast track to success—but the job might not be as legitimate as it sounds.",
      id: 14181,
      vote_count: 463,
      adult: false,
      backdrop_path: "/A96CVXbTNfhqw3jkUlyfFnGe8i3.jpg",
      release_date: "2000-02-18",
      genre_ids: [80, 18, 53],
      popularity: 8.977,
      character: "Chris Varick",
      credit_id: "52fe45d59251416c7506402f",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 263611,
      original_language: "es",
      original_title: "The Machine",
      overview: "",
      poster_path: null,
      release_date: "",
      title: "The Machine",
      video: false,
      vote_average: 8.2,
      vote_count: 5,
      popularity: 0.6,
      character: "",
      credit_id: "5343bb590e0a2679aa0057b3",
      order: 1,
    },
    {
      id: 279924,
      video: false,
      vote_count: 6,
      vote_average: 6.6,
      title: "The Making of 'The Iron Giant'",
      release_date: "2000-07-10",
      original_language: "en",
      original_title: "The Making of 'The Iron Giant'",
      genre_ids: [99],
      backdrop_path: null,
      adult: false,
      overview:
        "Documentary of the making of the animated family film, The Iron Giant.",
      poster_path: null,
      popularity: 1.553,
      character: "Himself",
      credit_id: "53b443550e0a26597d00cd61",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [878, 28],
      id: 374771,
      original_language: "en",
      original_title: "Riddick 4: Furya",
      overview:
        "When Riddick finally finds his home planet, he has no idea what's in store for him.",
      poster_path: "/lV5qk31axl9mo0uq9L4Jkmuzrbq.jpg",
      release_date: "",
      title: "Riddick 4: Furya",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 13.333,
      character: "Riddick",
      credit_id: "568245ae9251417ddd0135f0",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 297663,
      original_language: "en",
      original_title:
        "Breakin' in the USA:  Break Dancing and Electric Boogie Taught by the Pros",
      overview:
        "Breakdancing techniques are demonstrated by a group of dancers including a teenage Vin Diesel.",
      poster_path: "/A1YbMegnBEcbBxUs9c4ygZMIlua.jpg",
      release_date: "1984-01-01",
      title:
        "Breakin' in the USA:  Break Dancing and Electric Boogie Taught by the Pros",
      video: true,
      vote_average: 0,
      vote_count: 0,
      popularity: 1.952,
      character: "Himself",
      credit_id: "5a15c3069251413a05002ab1",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/j41s8FaIre8xSvXTpq9SzYJF6wj.jpg",
      genre_ids: [28, 12, 53, 80],
      id: 510710,
      original_language: "es",
      original_title: "Wheelman",
      overview: "",
      poster_path: "/7dFAiSgbTF71ODOJ6qmYAO2nhZW.jpg",
      release_date: "2009-03-24",
      title: "Wheelman",
      video: false,
      vote_average: 6.5,
      vote_count: 8,
      popularity: 2.686,
      character: "Milo Burik",
      credit_id: "5aa46896925141278d0144cd",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 35],
      id: 524595,
      original_language: "en",
      original_title: "Muscle",
      overview:
        "Vin Diesel will star in and produce the action-comedy “Muscle”",
      poster_path: null,
      release_date: "",
      title: "Muscle",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 0.6,
      character: "",
      credit_id: "5afc7bbfc3a36812a3000027",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 12, 53],
      id: 532805,
      original_language: "en",
      original_title: "xXx 4",
      overview: "Plot unknown",
      poster_path: "/6qpxFNEGzt0U8ndVEhnwgY6HrgE.jpg",
      release_date: "",
      title: "xXx 4",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 7.766,
      character: "Xander Cage",
      credit_id: "5b362bc7c3a368531d02c748",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28],
      id: 381834,
      original_language: "en",
      original_title: "Harbinger Wars",
      overview:
        'Plot unknown. Described as a crossover event film following "Harbinger" and "Bloodshot".',
      poster_path: null,
      release_date: "",
      title: "Harbinger Wars",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 0.6,
      character: "Ray Garrison / Bloodshot",
      credit_id: "5d303a9d6a300b1834a2cd5b",
      order: 1,
    },
    {
      id: 755679,
      original_title: "Fast & Furious 11",
      poster_path: "/qCNCbzJ2BVuoZN7Iee3UAtdTpnx.jpg",
      video: false,
      vote_average: 0,
      overview: "The final installment in The Fast Saga.",
      title: "Fast & Furious 11",
      vote_count: 0,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      genre_ids: [28, 80],
      popularity: 7.4,
      character: "Dominic Toretto",
      credit_id: "5f8f7f2717c4430036e454aa",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 878],
      id: 763759,
      original_language: "en",
      original_title: "Bloodshot 2",
      overview: "A sequel to the 2020 action film Bloodshot.",
      poster_path: null,
      release_date: "",
      title: "Bloodshot 2",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 1.4,
      character: "Ray Garrison / Bloodshot",
      credit_id: "5fae30d9ad59b500405a79bf",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 820529,
      original_language: "en",
      original_title: "'Rock 'Em Sock 'Em Robots'",
      overview:
        "A live action feature take on the on the classic tabletop boxing robots game.",
      poster_path: null,
      release_date: "",
      title: "'Rock 'Em Sock 'Em Robots'",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 0.6,
      character: "",
      credit_id: "607db8a32b8a43006ca10d4e",
      order: 1,
    },
    {
      id: 414701,
      video: false,
      vote_count: 2,
      vote_average: 6.5,
      title: "The Giant's Dream: The Making of the Iron Giant",
      release_date: "2016-09-06",
      original_language: "en",
      original_title: "The Giant's Dream: The Making of the Iron Giant",
      genre_ids: [99],
      backdrop_path: "/5L28dBqQEDfgq28M3rfCosKm55o.jpg",
      adult: false,
      overview:
        "A documentary about how the critically acclaimed film wound up being a box office disappointment, only to become regarded as a classic over a decade after its initial release.",
      poster_path: null,
      popularity: 1.4,
      character: "Himself",
      credit_id: "59082b4c9251416433009385",
      order: 2,
    },
    {
      video: false,
      vote_average: 7.9,
      overview:
        "In the small town of Rockwell, Maine in October 1957, a giant metal machine befriends a nine-year-old boy and ultimately finds its humanity by unselfishly saving people from their own fears and prejudices.",
      release_date: "1999-08-06",
      vote_count: 4140,
      adult: false,
      backdrop_path: "/wfClZdRb1x4LZ8B73Y9RSn8XAPa.jpg",
      id: 10386,
      genre_ids: [10751, 16, 12, 878, 35],
      title: "The Iron Giant",
      original_language: "en",
      original_title: "The Iron Giant",
      poster_path: "/bMr9Ir2hCFu2R72pjCA43uRMT4r.jpg",
      popularity: 67.299,
      character: "The Iron Giant (voice)",
      credit_id: "52fe43649251416c7500e873",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: "/uS6Vf7QIIfjyTUC1oYtTS7gN9dz.jpg",
      genre_ids: [80, 53],
      id: 7501,
      original_language: "en",
      original_title: "Knockaround Guys",
      overview:
        "Four sons of well-known New York mobsters must retrieve a bag of cash from a small Montana town ruled by a corrupt sheriff.",
      poster_path: "/oYqsIxxIfJMRHiNEMLzgG81brkY.jpg",
      release_date: "2001-09-07",
      title: "Knockaround Guys",
      video: false,
      vote_average: 5.9,
      vote_count: 240,
      popularity: 10.247,
      character: "Taylor Reese",
      credit_id: "52fe4480c3a36847f8099d19",
      order: 3,
    },
    {
      overview:
        "Light years from Earth, 26 years after being abducted, Peter Quill finds himself the prime target of a manhunt after discovering an orb wanted by Ronan the Accuser.",
      release_date: "2014-07-30",
      adult: false,
      backdrop_path: "/ko4N6wWp0UYlMmsVyfIfLyRAZtP.jpg",
      genre_ids: [28, 878, 12],
      id: 118340,
      original_language: "en",
      original_title: "Guardians of the Galaxy",
      poster_path: "/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
      vote_count: 22930,
      video: false,
      vote_average: 7.9,
      title: "Guardians of the Galaxy",
      popularity: 48.156,
      character: "Groot (voice)",
      credit_id: "52fe4bd5c3a36847f8215d5b",
      order: 3,
    },
    {
      id: 283995,
      genre_ids: [12, 28, 878, 35],
      original_language: "en",
      original_title: "Guardians of the Galaxy Vol. 2",
      poster_path: "/y4MBh0EjBlMuOzv9axM4qJlmhzz.jpg",
      video: false,
      vote_average: 7.6,
      overview:
        "The Guardians must fight to keep their newfound family together as they unravel the mysteries of Peter Quill's true parentage.",
      release_date: "2017-04-19",
      vote_count: 16968,
      title: "Guardians of the Galaxy Vol. 2",
      adult: false,
      backdrop_path: "/aJn9XeesqsrSLKcHfHP4u5985hn.jpg",
      popularity: 111.781,
      character: "Baby Groot (voice)",
      credit_id: "552616ab9251417248003723",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 448371,
      original_language: "en",
      original_title: "Guide to the Galaxy with James Gunn",
      overview:
        "The director and his 8-bit avatar lead you on a galactic adventure through the making of this epic movie, from vibrant concept art, elaborate makeup and amazing sets, to dancing baby Groot.",
      poster_path: "/6Npw2utmyIdfqYlXgSZnEeN1eBR.jpg",
      release_date: "2014-12-09",
      title: "Guide to the Galaxy with James Gunn",
      video: true,
      vote_average: 8.7,
      vote_count: 10,
      popularity: 2.93,
      character: "Himself",
      credit_id: "58d2b58c9251411faa0015c0",
      order: 3,
    },
    {
      poster_path: "/vblJ5cTqZKg3DSyN1z8JxTUyf2Y.jpg",
      video: false,
      vote_average: 5.9,
      id: 293767,
      overview:
        "19-year-old Billy Lynn is brought home for a victory tour after a harrowing Iraq battle. Through flashbacks the film shows what really happened to his squad - contrasting the realities of war with America's perceptions.",
      release_date: "2016-11-10",
      adult: false,
      backdrop_path: "/62Mjm9I9Ul6iUqe63NYM84dA4cm.jpg",
      vote_count: 424,
      genre_ids: [18, 10752],
      title: "Billy Lynn's Long Halftime Walk",
      original_language: "en",
      original_title: "Billy Lynn's Long Halftime Walk",
      popularity: 14.383,
      character: "Shroom",
      credit_id: "552d436ac3a3684ad6000ea8",
      order: 4,
    },
    {
      video: false,
      vote_average: 0,
      overview: "",
      release_date: "2024-12-18",
      title: "Avatar 3",
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 18, 878, 12, 14],
      vote_count: 0,
      original_language: "en",
      original_title: "Avatar 3",
      poster_path: null,
      id: 83533,
      popularity: 3.862,
      character: "",
      credit_id: "5cb50ae992514108cbf2f30e",
      order: 4,
    },
    {
      adult: false,
      backdrop_path: "/rpLOGbf71APcL6rJRaGpAOLUDfE.jpg",
      genre_ids: [28, 12, 878, 10770],
      id: 774752,
      original_language: "en",
      original_title: "The Guardians of the Galaxy Holiday Special",
      overview:
        "Before Star-Lord, Gamora, Drax, Rocket, Mantis and Groot hit the big screen with the next Guardians of the Galaxy film in 2023, watch the Guardians engage in some spirited shenanigans in an all-new original special, created for Disney+, during the 2022 holiday season.",
      poster_path: "/A7NLWwvgzlbg8RBJKPHlEszdD74.jpg",
      release_date: "",
      title: "The Guardians of the Galaxy Holiday Special",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 1.471,
      character: "Groot (voice)",
      credit_id: "5fd2c4ced20c87003e370b5b",
      order: 4,
    },
    {
      overview: "The third film based on Marvel's Guardians of the Galaxy.",
      release_date: "2023-05-03",
      title: "Guardians of the Galaxy Vol. 3",
      adult: false,
      backdrop_path: "/i9gxB3HjLNcWZzMD0vle41o4M3n.jpg",
      genre_ids: [28, 12, 878, 35],
      vote_count: 0,
      original_language: "en",
      original_title: "Guardians of the Galaxy Vol. 3",
      poster_path: "/1neAtYqPFfuyzpOnj3ZVDXtGXLf.jpg",
      vote_average: 0,
      video: false,
      id: 447365,
      popularity: 32.986,
      character: "Groot (voice)",
      credit_id: "5b7b79220e0a267c770030e2",
      order: 5,
    },
    {
      adult: false,
      backdrop_path: "/hjQp148VjWF4KjzhsD90OCMr11h.jpg",
      genre_ids: [18, 36, 10752],
      vote_count: 12023,
      original_language: "en",
      original_title: "Saving Private Ryan",
      poster_path: "/1wY4psJ5NVEhCuOYROwLH2XExM2.jpg",
      title: "Saving Private Ryan",
      video: false,
      vote_average: 8.2,
      id: 857,
      overview:
        "As U.S. troops storm the beaches of Normandy, three brothers lie dead on the battlefield, with a fourth trapped behind enemy lines. Ranger captain John Miller and seven men are tasked with penetrating German-held territory and bringing the boy home.",
      release_date: "1998-07-24",
      popularity: 39.854,
      character: "Private Adrian Caparzo",
      credit_id: "52fe4283c3a36847f8024b25",
      order: 6,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 224880,
      original_language: "en",
      original_title: "Playboy Mansion Parties Uncensored",
      overview:
        "See inside the exclusive Playboy Mansion, with parties attended by all the A-List celebrities",
      poster_path: null,
      release_date: "2001-05-31",
      title: "Playboy Mansion Parties Uncensored",
      video: true,
      vote_average: 7,
      vote_count: 3,
      popularity: 1.528,
      character: "Himself",
      credit_id: "5ae89babc3a368316f000526",
      order: 11,
    },
    {
      title: "Thor: Love and Thunder",
      genre_ids: [28, 12, 14, 35, 878],
      id: 616037,
      overview:
        "The fourth installment of the Marvel Studios' Thor movie series.",
      original_title: "Thor: Love and Thunder",
      poster_path: "/ifx23jgqQ8ZjUb9eiGjwbKtf0qQ.jpg",
      vote_average: 0,
      adult: false,
      backdrop_path: "/qB3HdCZKHWU33k9QYTIZaM4v5qo.jpg",
      video: false,
      vote_count: 0,
      release_date: "2022-04-28",
      original_language: "en",
      popularity: 25.311,
      character: "Groot (voice)",
      credit_id: "601a1e4ee942ee0042f5dffb",
      order: 11,
    },
    {
      id: 299536,
      vote_average: 8.3,
      overview:
        "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
      release_date: "2018-04-25",
      adult: false,
      backdrop_path: "/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg",
      vote_count: 22427,
      genre_ids: [12, 28, 878],
      video: false,
      original_language: "en",
      original_title: "Avengers: Infinity War",
      poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
      title: "Avengers: Infinity War",
      popularity: 417.041,
      character: "Groot (voice)",
      credit_id: "57eb6cf6c3a36868bd003830",
      order: 22,
    },
    {
      original_title: "Ralph Breaks the Internet",
      poster_path: "/qEnH5meR381iMpmCumAIMswcQw2.jpg",
      video: false,
      vote_average: 7.2,
      overview:
        "Video game bad guy Ralph and fellow misfit Vanellope von Schweetz must risk it all by traveling to the World Wide Web in search of a replacement part to save Vanellope's video game, Sugar Rush. In way over their heads, Ralph and Vanellope rely on the citizens of the internet — the netizens — to help navigate their way, including an entrepreneur named Yesss, who is the head algorithm and the heart and soul of trend-making site BuzzzTube.",
      release_date: "2018-11-20",
      vote_count: 5716,
      adult: false,
      backdrop_path: "/qDQEQbgP3v7B9IYLAUcYexNrVYP.jpg",
      title: "Ralph Breaks the Internet",
      genre_ids: [10751, 16, 35, 12],
      id: 404368,
      original_language: "en",
      popularity: 82.773,
      character: "Baby Groot (voice)",
      credit_id: "5bfd6197925141108002dc9c",
      order: 31,
    },
    {
      video: false,
      vote_average: 8.3,
      overview:
        "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
      release_date: "2019-04-24",
      adult: false,
      backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
      id: 299534,
      genre_ids: [12, 878, 28],
      vote_count: 18815,
      original_language: "en",
      original_title: "Avengers: Endgame",
      poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      title: "Avengers: Endgame",
      popularity: 271.227,
      character: "Groot (voice)",
      credit_id: "5e85d6d93344c6001740d4eb",
      order: 38,
    },
    {
      adult: false,
      backdrop_path: "/kZ8RDjMwEfqp7AluTrCImAVpCdX.jpg",
      genre_ids: [53, 80, 9648],
      id: 11092,
      original_language: "en",
      original_title: "Presumed Innocent",
      overview:
        "Rusty Sabich is a deputy prosecutor engaged in an obsessive affair with a coworker who is murdered. Soon after, he's accused of the crime. And his fight to clear his name becomes a whirlpool of lies and hidden passions.",
      poster_path: "/jSPWptOsqU1nxXQe6muSPB0kD3c.jpg",
      release_date: "1990-07-26",
      title: "Presumed Innocent",
      video: false,
      vote_average: 6.8,
      vote_count: 454,
      popularity: 8.913,
      character: "Extra (uncredited)",
      credit_id: "5c13fe620e0a2603883bc44a",
      order: 39,
    },
    {
      adult: false,
      backdrop_path: "/oUNAGuc28xNxeUg2NpXuT3qKup0.jpg",
      genre_ids: [18],
      id: 11005,
      original_language: "en",
      original_title: "Awakenings",
      overview:
        'Dr. Malcolm Sayer, a shy research physician, uses an experimental drug to "awaken" the catatonic victims of a rare disease. Leonard is the first patient to receive the controversial treatment. His awakening, filled with awe and enthusiasm, proves a rebirth for Sayer too, as the exuberant patient reveals life\'s simple but unutterably sweet pleasures to the introverted doctor.',
      poster_path: "/9gztZXuHLG6AJ0fgqGd7Q43cWRI.jpg",
      release_date: "1990-12-04",
      title: "Awakenings",
      video: false,
      vote_average: 7.7,
      vote_count: 1714,
      popularity: 9.269,
      character: "Hospital Orderly (Uncredited)",
      credit_id: "52fe43e09251416c75021a17",
      order: 42,
    },
    {
      original_language: "en",
      id: 259910,
      poster_path: "/41Ke02UzYoPsiTc3YbomPGiQKMl.jpg",
      video: false,
      title: "Marvel Studios: Assembling a Universe",
      overview:
        'A look at the story behind Marvel Studios and the Marvel Cinematic Universe, featuring interviews and behind-the-scenes footage from all of the Marvel films, the Marvel One-Shots and "Marvel\'s Agents of S.H.I.E.L.D."',
      release_date: "2014-03-18",
      vote_count: 113,
      adult: false,
      backdrop_path: "/czHz1DWWE0bcffXybT7u1wNshSx.jpg",
      vote_average: 7,
      genre_ids: [10770, 99],
      original_title: "Marvel Studios: Assembling a Universe",
      popularity: 12.982,
      character: "Self",
      credit_id: "5537d7669251411256002f30",
      order: 43,
    },
    {
      adult: false,
      backdrop_path: "/dMARcKLrv0T7kVJ4iQR3vqTTdtT.jpg",
      genre_ids: [28, 80, 18, 53],
      id: 9615,
      original_language: "en",
      original_title: "The Fast and the Furious: Tokyo Drift",
      overview:
        "In order to avoid a jail sentence, Sean Boswell heads to Tokyo to live with his military father. In a low-rent section of the city, Shaun gets caught up in the underground world of drift racing",
      poster_path: "/cm2ffqb3XovzA5ZSzyN3jnn8qv0.jpg",
      release_date: "2006-06-03",
      title: "The Fast and the Furious: Tokyo Drift",
      video: false,
      vote_average: 6.3,
      vote_count: 4877,
      popularity: 11.216,
      character: "Dominic Toretto (uncredited)",
      credit_id: "544316b1c3a3683e01003444",
      order: 53,
    },
  ],
  crew: [
    {
      id: 15803,
      video: false,
      vote_count: 16,
      vote_average: 6.6,
      title: "Multi-Facial",
      release_date: "1995-01-01",
      original_language: "en",
      original_title: "Multi-Facial",
      genre_ids: [18],
      backdrop_path: null,
      adult: false,
      overview:
        "Through a series of auditions, a young actor in New York City struggles with his identity.",
      poster_path: null,
      popularity: 1.74,
      credit_id: "52fe467e9251416c7507a1cd",
      department: "Directing",
      job: "Director",
    },
    {
      overview:
        "Rick (Diesel) is frustrated by the repetitious grind of one-night stands and aimless hustling. Whilst looking for more to his life he meets Heather (Lanza), a neighbour. Rick takes the opportunity to escape his boring life style with her, but soon finds that his volatile behaviour threatens to finish their relationship before it even really begins.",
      release_date: "1997-01-18",
      adult: false,
      backdrop_path: null,
      id: 19083,
      genre_ids: [18],
      vote_count: 24,
      original_language: "en",
      original_title: "Strays",
      poster_path: "/mF6LBmWNAy9LSzy9JWF4IBYOy1l.jpg",
      video: false,
      title: "Strays",
      vote_average: 5.1,
      popularity: 2.87,
      credit_id: "52fe47b89251416c750a3473",
      department: "Directing",
      job: "Director",
    },
    {
      original_language: "en",
      original_title: "Los Bandoleros",
      poster_path: "/rqWRTgjHcmcmeRXE1w1LyYZupwS.jpg",
      video: false,
      vote_average: 6.4,
      overview:
        "The film tells the back story about the characters and events leading up to the explosive oil truck heist in Fast &amp; Furious.",
      release_date: "2009-07-28",
      id: 253835,
      title: "Los Bandoleros",
      adult: false,
      backdrop_path: "/uijC23zReJLR3xUq3xh41NuI6vG.jpg",
      genre_ids: [28, 18],
      vote_count: 264,
      popularity: 0.692,
      credit_id: "52fe4e959251416c9113697d",
      department: "Directing",
      job: "Director",
    },
    {
      original_title: "The Chronicles of Riddick",
      poster_path: "/iSaB7jBgsU6sXqKneZpdeRw5MSV.jpg",
      video: false,
      vote_average: 6.5,
      title: "The Chronicles of Riddick",
      overview:
        "After years of outrunning ruthless bounty hunters, escaped convict Riddick suddenly finds himself caught between opposing forces in a fight for the future of the human race. Now, waging incredible battles on fantastic and deadly worlds, this lone, reluctant hero will emerge as humanity's champion - and the last hope for a universe on the edge of annihilation.",
      release_date: "2004-06-11",
      id: 2789,
      adult: false,
      backdrop_path: "/9o0WHLPvHHAznN0H3pBfjjiFioN.jpg",
      genre_ids: [28, 878],
      vote_count: 3073,
      original_language: "en",
      popularity: 13.203,
      credit_id: "52fe436dc3a36847f8053777",
      department: "Production",
      job: "Producer",
    },
    {
      id: 8409,
      adult: false,
      backdrop_path: "/tQVJJ2kODGU0N7UnyPauv0qk8ag.jpg",
      genre_ids: [28, 18],
      original_language: "en",
      original_title: "A Man Apart",
      poster_path: "/z0JUBNk4BTBmeMOudrRH9GnOmK0.jpg",
      video: false,
      vote_average: 6.1,
      vote_count: 648,
      overview:
        "When Vetter's wife is killed in a botched hit organized by Diablo, he seeks revenge against those responsible. But in the process, Vetter and Hicks have to fight their way up the chain to get to Diablo but it's easier said than done when all Vetter can focus on is revenge.",
      release_date: "2003-04-04",
      title: "A Man Apart",
      popularity: 13.818,
      credit_id: "52fe44a5c3a36847f80a21a3",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/3ZiM6gm2XL8qnhZCXsTjixvaH4v.jpg",
      genre_ids: [28, 80, 18, 53],
      id: 13804,
      original_language: "en",
      original_title: "Fast & Furious",
      overview:
        "When a crime brings them back to L.A., fugitive ex-con Dom Toretto reignites his feud with agent Brian O'Conner. But as they are forced to confront a shared enemy, Dom and Brian must give in to an uncertain new trust if they hope to outmaneuver him. And the two men will find the best way to get revenge: push the limits of what's possible behind the wheel.",
      poster_path: "/fjGCa4oLvgpMVF2jawbjXBWp91v.jpg",
      release_date: "2009-04-02",
      title: "Fast & Furious",
      video: false,
      vote_average: 6.7,
      vote_count: 5529,
      popularity: 13.632,
      credit_id: "52fe45a39251416c7505d3bf",
      department: "Production",
      job: "Producer",
    },
    {
      id: 15803,
      video: false,
      vote_count: 16,
      vote_average: 6.6,
      title: "Multi-Facial",
      release_date: "1995-01-01",
      original_language: "en",
      original_title: "Multi-Facial",
      genre_ids: [18],
      backdrop_path: null,
      adult: false,
      overview:
        "Through a series of auditions, a young actor in New York City struggles with his identity.",
      poster_path: null,
      popularity: 1.74,
      credit_id: "52fe467e9251416c7507a1d9",
      department: "Production",
      job: "Producer",
    },
    {
      overview:
        "Former cop Brian O'Conner partners with ex-con Dom Toretto on the opposite side of the law. Since Brian and Mia Toretto broke Dom out of custody, they've blown across many borders to elude authorities. Now backed into a corner in Rio de Janeiro, they must pull one last job in order to gain their freedom.",
      release_date: "2011-04-20",
      adult: false,
      backdrop_path: "/lvSxooYCRuF3S2kHWXYTrcOtYco.jpg",
      id: 51497,
      genre_ids: [28, 53, 80],
      original_language: "en",
      original_title: "Fast Five",
      poster_path: "/vDztZS30sheoqnJnKyO4QMnf3f8.jpg",
      vote_count: 6231,
      video: false,
      vote_average: 7.3,
      title: "Fast Five",
      popularity: 10.517,
      credit_id: "52fe47f6c3a36847f8151af1",
      department: "Production",
      job: "Producer",
    },
    {
      id: 82992,
      adult: false,
      backdrop_path: "/mRfI3y2oAd7ejur2di09xC9niqp.jpg",
      genre_ids: [28, 53, 80],
      original_language: "en",
      original_title: "Fast & Furious 6",
      poster_path: "/n31VRDodbaZxkrZmmzyYSFNVpW5.jpg",
      vote_count: 8823,
      video: false,
      vote_average: 6.8,
      title: "Fast & Furious 6",
      overview:
        "Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets convoluted also facing his presumed deceased girlfriend, Letty.",
      release_date: "2013-05-21",
      popularity: 9.604,
      credit_id: "52fe48839251416c9108f059",
      department: "Production",
      job: "Producer",
    },
    {
      genre_ids: [878, 28, 53],
      original_language: "en",
      original_title: "Riddick",
      poster_path: "/xhdDd6Gd6EaPBwNdCjNW2HCnIQY.jpg",
      video: false,
      vote_average: 6.3,
      vote_count: 3222,
      overview:
        "Betrayed by his own kind and left for dead on a desolate planet, Riddick fights for survival against alien predators and becomes more powerful and dangerous than ever before. Soon bounty hunters from throughout the galaxy descend on Riddick only to find themselves pawns in his greater scheme for revenge. With his enemies right where he wants them, Riddick unleashes a vicious attack of vengeance before returning to his home planet of Furya to save it from destruction.",
      release_date: "2013-09-02",
      title: "Riddick",
      id: 87421,
      adult: false,
      backdrop_path: "/naGU49u4BXynQ1o5L755pfs8dom.jpg",
      popularity: 24.358,
      credit_id: "52fe49c39251416c910b8131",
      department: "Production",
      job: "Producer",
    },
    {
      id: 168259,
      vote_average: 7.3,
      overview:
        "Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
      release_date: "2015-04-01",
      adult: false,
      backdrop_path: "/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg",
      vote_count: 8589,
      genre_ids: [28, 53, 80, 12],
      video: false,
      original_language: "en",
      original_title: "Furious 7",
      poster_path: "/wurKlC3VKUgcfsn0K51MJYEleS2.jpg",
      title: "Furious 7",
      popularity: 115.257,
      credit_id: "52fe4cc8c3a36847f823e681",
      department: "Production",
      job: "Producer",
    },
    {
      original_language: "en",
      original_title: "xXx",
      poster_path: "/86BnliVDBo2TjKmrgQTJIPHxAKd.jpg",
      video: false,
      vote_average: 5.9,
      title: "xXx",
      overview:
        'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he\'s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.',
      release_date: "2002-08-09",
      vote_count: 3245,
      adult: false,
      backdrop_path: "/qwK9soQmmJ7kRdjLZVXblw3g7AQ.jpg",
      id: 7451,
      genre_ids: [28, 12, 53],
      popularity: 22.153,
      credit_id: "538d8bf5c3a3687152004768",
      department: "Production",
      job: "Executive Producer",
    },
    {
      original_language: "en",
      original_title: "Los Bandoleros",
      poster_path: "/rqWRTgjHcmcmeRXE1w1LyYZupwS.jpg",
      video: false,
      vote_average: 6.4,
      overview:
        "The film tells the back story about the characters and events leading up to the explosive oil truck heist in Fast &amp; Furious.",
      release_date: "2009-07-28",
      id: 253835,
      title: "Los Bandoleros",
      adult: false,
      backdrop_path: "/uijC23zReJLR3xUq3xh41NuI6vG.jpg",
      genre_ids: [28, 18],
      vote_count: 264,
      popularity: 0.692,
      credit_id: "550d553c92514133c30034c5",
      department: "Production",
      job: "Producer",
    },
    {
      video: false,
      vote_average: 6.9,
      overview:
        "When a mysterious woman seduces Dom into the world of crime and a betrayal of those closest to him, the crew face trials that will test them as never before.",
      release_date: "2017-04-12",
      adult: false,
      backdrop_path: "/jzdnhRhG0dsuYorwvSqPqqnM1cV.jpg",
      vote_count: 8440,
      genre_ids: [28, 80, 53],
      id: 337339,
      original_language: "en",
      original_title: "The Fate of the Furious",
      poster_path: "/dImWM7GJqryWJO9LHa3XQ8DD5NH.jpg",
      title: "The Fate of the Furious",
      popularity: 156.067,
      credit_id: "553ea93f92514138a900b0a5",
      department: "Production",
      job: "Producer",
    },
    {
      vote_count: 4524,
      id: 47971,
      video: false,
      overview:
        "Extreme athlete turned government operative Xander Cage comes out of self-imposed exile, thought to be long dead, and is set on a collision course with deadly alpha warrior Xiang and his team in a race to recover a sinister and seemingly unstoppable weapon known as Pandora's Box. Recruiting an all-new group of thrill-seeking cohorts, Xander finds himself enmeshed in a deadly conspiracy that points to collusion at the highest levels of world governments.",
      release_date: "2017-01-13",
      backdrop_path: "/7KAXYsemH14agl4ohhNeIxwWXhj.jpg",
      original_language: "en",
      adult: false,
      poster_path: "/hba8zREJpP1AYhaXgb2oJLQeO0K.jpg",
      original_title: "xXx: Return of Xander Cage",
      genre_ids: [28, 12, 80],
      vote_average: 5.9,
      title: "xXx: Return of Xander Cage",
      popularity: 70.919,
      credit_id: "5693ca989251415c30000028",
      department: "Production",
      job: "Producer",
    },
    {
      id: 274854,
      adult: false,
      backdrop_path: "/g8DUZrgCfXRJ5CazfZ5X7qCWcvZ.jpg",
      genre_ids: [14, 28, 12, 878],
      original_language: "en",
      original_title: "The Last Witch Hunter",
      poster_path: "/qXvOpA2nhK5HQ6I95sN3nnMtfjH.jpg",
      vote_count: 2935,
      title: "The Last Witch Hunter",
      vote_average: 5.9,
      video: false,
      overview:
        "The modern world holds many secrets, but by far the most astounding is that witches still live among us; vicious supernatural creatures intent on unleashing the Black Death upon the world and putting an end to the human race once and for all. Armies of witch hunters have battled this unnatural enemy for centuries, including Kaulder, a valiant warrior who many years ago slayed the all-powerful Witch Queen, decimating her followers in the process. In the moments right before her death, the Queen cursed Kaulder with immortality, forever separating him from his beloved wife and daughter. Today, Kaulder is the last living hunter who has spent his immortal life tracking down rogue witches, all the while yearning for his long-lost family.",
      release_date: "2015-10-21",
      popularity: 43.449,
      credit_id: "56a4fd0392514172070074f6",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 35],
      id: 524595,
      original_language: "en",
      original_title: "Muscle",
      overview:
        "Vin Diesel will star in and produce the action-comedy “Muscle”",
      poster_path: null,
      release_date: "",
      title: "Muscle",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 0.6,
      credit_id: "5afc7bdbc3a3681293000036",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [28, 12, 53],
      id: 532805,
      original_language: "en",
      original_title: "xXx 4",
      overview: "Plot unknown",
      poster_path: "/6qpxFNEGzt0U8ndVEhnwgY6HrgE.jpg",
      release_date: "",
      title: "xXx 4",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 7.766,
      credit_id: "5b362b28c3a368532f02e605",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [878, 28],
      id: 374771,
      original_language: "en",
      original_title: "Riddick 4: Furya",
      overview:
        "When Riddick finally finds his home planet, he has no idea what's in store for him.",
      poster_path: "/lV5qk31axl9mo0uq9L4Jkmuzrbq.jpg",
      release_date: "",
      title: "Riddick 4: Furya",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 13.333,
      credit_id: "5d384bf1b0460500108ddf75",
      department: "Production",
      job: "Executive Producer",
    },
    {
      release_date: "2021-05-19",
      adult: false,
      backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
      genre_ids: [28, 80, 53],
      vote_count: 2685,
      original_language: "en",
      original_title: "F9",
      poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
      title: "F9",
      video: false,
      vote_average: 7.7,
      id: 385128,
      overview:
        "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
      popularity: 3309.679,
      credit_id: "5f448b2441429100354fb69d",
      department: "Production",
      job: "Producer",
    },
    {
      original_title: "Bloodshot",
      id: 338762,
      video: false,
      vote_average: 6.9,
      overview:
        "After he and his wife are murdered, marine Ray Garrison is resurrected by a team of scientists. Enhanced with nanotechnology, he becomes a superhuman, biotech killing machine—'Bloodshot'. As Ray first trains with fellow super-soldiers, he cannot recall anything from his former life. But when his memories flood back and he remembers the man that killed both him and his wife, he breaks out of the facility to get revenge, only to discover that there's more to the conspiracy than he thought.",
      release_date: "2020-03-05",
      title: "Bloodshot",
      adult: false,
      backdrop_path: "/zlqMASc3vEtdym2OvXgE7fC6onT.jpg",
      vote_count: 3934,
      genre_ids: [28, 878],
      poster_path: "/8WUVHemHFH2ZIP6NWkwlHWsyrEL.jpg",
      original_language: "en",
      popularity: 338.78,
      credit_id: "5f89b8302667780038e00e94",
      department: "Production",
      job: "Producer",
    },
    {
      id: 755679,
      original_title: "Fast & Furious 11",
      poster_path: "/qCNCbzJ2BVuoZN7Iee3UAtdTpnx.jpg",
      video: false,
      vote_average: 0,
      overview: "The final installment in The Fast Saga.",
      title: "Fast & Furious 11",
      vote_count: 0,
      adult: false,
      backdrop_path: null,
      original_language: "en",
      genre_ids: [28, 80],
      popularity: 7.4,
      credit_id: "5f8f7e14c048a900384070b5",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [],
      id: 820529,
      original_language: "en",
      original_title: "'Rock 'Em Sock 'Em Robots'",
      overview:
        "A live action feature take on the on the classic tabletop boxing robots game.",
      poster_path: null,
      release_date: "",
      title: "'Rock 'Em Sock 'Em Robots'",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 0.6,
      credit_id: "607db8b643d9b100290787d4",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/ntEHvLm7QLHpcw3EGmH1aXyziwP.jpg",
      genre_ids: [28, 53, 18],
      id: 1620,
      original_language: "en",
      original_title: "Hitman",
      overview:
        'A genetically engineered assassin with deadly aim, known only as "Agent 47" eliminates strategic targets for a top-secret organization. But when he\'s double-crossed, the hunter becomes the prey as 47 finds himself in a life-or-death game of international intrigue.',
      poster_path: "/h69UJOOKlrHcvhl5H2LY74N61DQ.jpg",
      release_date: "2007-11-21",
      title: "Hitman",
      video: false,
      vote_average: 6.1,
      vote_count: 2455,
      popularity: 26.828,
      credit_id: "60e788f29979d20025a4636d",
      department: "Production",
      job: "Executive Producer",
    },
    {
      id: 15803,
      video: false,
      vote_count: 16,
      vote_average: 6.6,
      title: "Multi-Facial",
      release_date: "1995-01-01",
      original_language: "en",
      original_title: "Multi-Facial",
      genre_ids: [18],
      backdrop_path: null,
      adult: false,
      overview:
        "Through a series of auditions, a young actor in New York City struggles with his identity.",
      poster_path: null,
      popularity: 1.74,
      credit_id: "52fe467e9251416c7507a1d3",
      department: "Writing",
      job: "Writer",
    },
    {
      overview:
        "Rick (Diesel) is frustrated by the repetitious grind of one-night stands and aimless hustling. Whilst looking for more to his life he meets Heather (Lanza), a neighbour. Rick takes the opportunity to escape his boring life style with her, but soon finds that his volatile behaviour threatens to finish their relationship before it even really begins.",
      release_date: "1997-01-18",
      adult: false,
      backdrop_path: null,
      id: 19083,
      genre_ids: [18],
      vote_count: 24,
      original_language: "en",
      original_title: "Strays",
      poster_path: "/mF6LBmWNAy9LSzy9JWF4IBYOy1l.jpg",
      video: false,
      title: "Strays",
      vote_average: 5.1,
      popularity: 2.87,
      credit_id: "52fe47b89251416c750a3479",
      department: "Writing",
      job: "Writer",
    },
    {
      original_language: "en",
      original_title: "Los Bandoleros",
      poster_path: "/rqWRTgjHcmcmeRXE1w1LyYZupwS.jpg",
      video: false,
      vote_average: 6.4,
      overview:
        "The film tells the back story about the characters and events leading up to the explosive oil truck heist in Fast &amp; Furious.",
      release_date: "2009-07-28",
      id: 253835,
      title: "Los Bandoleros",
      adult: false,
      backdrop_path: "/uijC23zReJLR3xUq3xh41NuI6vG.jpg",
      genre_ids: [28, 18],
      vote_count: 264,
      popularity: 0.692,
      credit_id: "52fe4e959251416c91136983",
      department: "Writing",
      job: "Writer",
    },
  ],
  id: 12835,
};

export const genres = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Documentary",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10402: "Music",
  9648: "Mystery",
  10749: "Romance",
  878: "Science Fiction",
  10770: "TV Movie",
  53: "Thriller",
  10752: "War",
  37: "Western",
};

export const examplePerson = {
  adult: false,
  also_known_as: [
    "Mark Sinclair Vincent",
    "Mark Vincent",
    "Він Дізель",
    "Вин Дизель",
    "فان ديزل",
    "วิน ดีเซล",
    "ヴィン・ディーゼル",
    "빈 디젤",
    "馮·迪索",
    "Βιν Ντίζελ",
    "范·迪塞尔",
    "വിൻ ഡീസൽ",
  ],
  biography:
    "Mark Sinclair (born 18 July 1967), known professionally as Vin Diesel, is an American actor, producer, director and screenwriter. He is best known for playing Dominic Toretto in the Fast & Furious franchise and is one of the highest-grossing actors of all time.\n\nHe began his career in 1990 but struggled to gain roles until he wrote, directed, produced, scored, and starred in the short film Multi-Facial (1995). This attracted the attention of Steven Spielberg, who was developing Saving Private Ryan (1998); Spielberg re-wrote elements of the film to allow Diesel to appear. He subsequently voiced the titular character in The Iron Giant (1999) while gaining a reputation as an action star after headlining the Fast & Furious, XXX, and The Chronicles of Riddick film franchises.\n\nDiesel voiced Groot in Guardians of the Galaxy (2014) and its sequel (2017), as well as Ralph Breaks the Internet (2018). Away from action films, he has enjoyed commercial success in a number of other genres, such as the comedy film The Pacifier (2005), while his performance in Find Me Guilty (2006) was praised. Diesel portrayed the comic book superhero Bloodshot in its 2020 film adaptation and is slated to appear in the Avatar sequels.\n\nHe founded the production company One Race Films, where he has also served as a producer or executive producer for a number of his star vehicles. Diesel also founded the record label Racetrack Records and video game developer Tigon Studios and has provided his voice and motion capture for all of Tigon's releases.\n\nFrom Wikipedia, the free encyclopedia",
  birthday: "1967-07-18",
  deathday: null,
  gender: 2,
  homepage: null,
  id: 12835,
  imdb_id: "nm0004874",
  known_for_department: "Acting",
  name: "Vin Diesel",
  place_of_birth: "Alameda County, California, USA",
  popularity: 32.986,
  profile_path: "/7rwSXluNWZAluYMOEWBxkPmckES.jpg",
};
