export const exampleMovieCredits = {
  cast: [
    {
      adult: false,
      backdrop_path: "/d9AlGSzSx0Xl9gjs5lGXu0J1yeY.jpg",
      genre_ids: [10749, 35],
      id: 79321,
      original_language: "zh",
      original_title: "五月之恋",
      overview: "A girl from china meets a taiwanese boy chatting",
      poster_path: "/AcYpWmErcajhQoXBaRCnaqjMPYR.jpg",
      release_date: "2004-07-16",
      title: "Love of May",
      video: false,
      vote_average: 8,
      vote_count: 1,
      popularity: 0.882,
      character: "Crystal Liu",
      credit_id: "52fe49ccc3a368484e140611",
      order: 0,
    },
    {
      overview:
        "Bai Qian, a goddess and monarch from the Heavenly Realms, is sent to the mortal world to undergo a trial to become a High Goddess. There, she meets Ye Hua, with whom she falls in love and marries. When an old enemy reappears in her life, everything she holds dear is threatened.",
      id: 463197,
      adult: false,
      backdrop_path: "/xnzJdbbxWfDCvQdZay9HRjVPQmf.jpg",
      title: "Once Upon a Time",
      genre_ids: [18, 14, 10749],
      original_language: "zh",
      original_title: "三生三世十里桃花",
      poster_path: "/n3O8ZQrXS3WEZwVbzjtY7jXqMfw.jpg",
      vote_count: 19,
      video: false,
      vote_average: 7.9,
      release_date: "2017-08-03",
      popularity: 3.462,
      character: "Bai Qian / Si Yin / Su Su",
      credit_id: "594e5d7dc3a368328b03284e",
      order: 0,
    },
    {
      poster_path: "/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg",
      video: false,
      vote_average: 7,
      id: 337401,
      overview:
        "When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.",
      release_date: "2020-09-04",
      adult: false,
      backdrop_path: "/aoHiMjRt0Qs1dtkV61LyxTnQtJl.jpg",
      vote_count: 5031,
      genre_ids: [12, 14],
      title: "Mulan",
      original_language: "en",
      original_title: "Mulan",
      popularity: 194.648,
      character: "Hua Mulan",
      credit_id: "5a1f27efc3a3680b930821c6",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/f6MlqTGJzr9t4AbbobUc2d9ybWY.jpg",
      genre_ids: [35, 14],
      vote_count: 13,
      original_language: "zh",
      original_title: "二代妖精之今生有幸",
      poster_path: "/zs4kWMWg5SWoqdQsP3EmY8LetLI.jpg",
      id: 492317,
      video: false,
      vote_average: 6.1,
      title: "Hanson and the Beast",
      overview:
        "Yuan Shuai, a debt-ridden animal-breeder, tries to get out of his financial predicament by finding a wealthy girlfriend through matchmaking dates. He unexpectedly meets and fall in love with the fox demon, Bai Xianchu, who has arrived to the mortal realm to repay her gratitude. However, the head of the Demon tribe Yun Zhonghe forbids a love relationship between a demon and a human; and takes Bai Xianchu away. To seek his lover, Yuan Shuai bravely crashes the demonic world.",
      release_date: "2017-12-29",
      popularity: 2.649,
      character: "Bai Xianchu",
      credit_id: "5a39a191c3a3680b8d203cc7",
      order: 0,
    },
    {
      overview:
        "It’s 1941 and the Japanese attack on Pearl Harbor has destroyed America’s morale. The US President Franklin D. Roosevelt then decides to risk it all by bombing Tokyo and raise more hope for his citizens. After completing its mission, a unit of the US Air Force is forced to make an emergency landing in China. Its commander Jack Turner (Emilie Hirsch) barely survives but gets rescued by Ying (Crystal Liu), a local widow who will stop at nothing to hide him from the Japanese occupant.",
      release_date: "2017-11-10",
      id: 528210,
      title: "The Chinese Widow",
      adult: false,
      backdrop_path: "/430DV9AgQ4mV8WjahXDvMKEfOHJ.jpg",
      genre_ids: [18, 10749, 36, 10752],
      original_language: "zh",
      original_title: "烽火芳菲",
      poster_path: "/ztcaeAzK3VkllaWB0VEQdcSD7BO.jpg",
      vote_count: 102,
      video: false,
      vote_average: 7.4,
      popularity: 6.279,
      character: "Ying",
      credit_id: "5b1482340e0a262de2003e24",
      order: 0,
    },
    {
      video: false,
      vote_average: 5.8,
      overview:
        '"For Love or Money" is based on a novel by Zhang Xiaoxian, which tells the moving story between a fallen noble lady and a rich heir to a large company. She’s broken and has lost the direction in life, whereas he chooses a life of poverty and freedom to pursue his passion as a painter. Together, will they be able to find themselves in this world of twists and turns before it’s too late?',
      release_date: "2014-11-07",
      vote_count: 5,
      adult: false,
      backdrop_path: null,
      title: "For Love or Money",
      genre_ids: [10749],
      id: 305088,
      original_language: "zh",
      original_title: "露水紅顏",
      poster_path: "/99PEQzwbhqLGQtvqmrCPRPavyEa.jpg",
      popularity: 1.316,
      character: "Xing Lu",
      credit_id: "546efedd92514112e700143c",
      order: 1,
    },
    {
      id: 49704,
      video: false,
      vote_count: 13,
      vote_average: 5.7,
      title: "Love in Disguise",
      release_date: "2010-08-12",
      original_language: "zh",
      original_title: "戀愛通告",
      genre_ids: [35, 10749],
      backdrop_path: "/472oPMatT3EMvJX9jn0Ep7QZHKJ.jpg",
      adult: false,
      overview:
        "Famous from an incredibly young age, DMH (Wang Lee Hom) has only ever known a celebrity pop star existence. Yet, despite all the glamour, there is still something lacking in his charmed life - true love. With the help of fellow musician and friend WZB, DMH disguised himself as a regular Joe in the hope of finding true love. While incognito, DMH and WZB stumble across the performance of a classical Chinese orchestra and DMH is immediately captivated by the melodies of the guzheng soloist, LMQ (Crystal Liu Yi-Fei), a student at the Shanghai Conservatory, whose affections lie with the accomplished but arrogant virtuoso, ZXZ. In his attempt to spend more time with LQM, DMH promises to help LQM get together with ZXZ. As DMH and LQM grow closer, it becomes increasingly difficult to conceal his identity.",
      poster_path: "/lyJZF8dArtLhK1C0LYX1EXgDAuv.jpg",
      popularity: 1.4,
      character: "Song Xiao-Qing",
      credit_id: "52fe47a1c3a36847f81402eb",
      order: 1,
    },
    {
      id: 70530,
      adult: false,
      backdrop_path: "/8fBd83OUla3QpiSWjPUzwuOO5cs.jpg",
      genre_ids: [14, 28],
      original_language: "cn",
      original_title: "倩女幽魂",
      poster_path: "/zKigVU0hX69Nzf2GyDF1O9tZpEJ.jpg",
      video: false,
      vote_average: 5.6,
      vote_count: 34,
      overview:
        "Government official Ling Choi Sin journeys to the parched Black Mountain Village, to help its inhabitants find water.  As he leads a group of volunteers up the haunted mountain, he encounters a bevy of sexy demons as well as a lovely girl named Siu Sin.  After wooing her with some candy, he falls for her... and then realises that he is caught in a deadly triangle; another guy, a demon-hunter named Yan Chek Ha is also in love with Siu Sin.  However, before the two men can settle their differences, they have to contend with the evil Tree Demon as well as a one-armed demon hunter who is determined to kill all the supernatural beings.",
      release_date: "2011-04-21",
      title: "A Chinese Ghost Story , A Chinese Fairy Tale",
      popularity: 4.828,
      character: "Siu Sin",
      credit_id: "52fe47fec3a368484e0e453b",
      order: 1,
    },
    {
      poster_path: "/iflthXJoh1jDND6CWCrEAG9JgwT.jpg",
      video: false,
      vote_average: 5.5,
      overview:
        "In the year 198 BC, Cao Cao (Chow Yun Fat), Prime Minister of the Han Dynasty, ventured to the east and defeated China's greatest warrior Lu Bu, terrifying every ambitious warlord across the country. Several years later, after taking the Han Emperor under his wing, Cao crowns himself King of Wei. He built a magnificent Bronze Sparrow Island to symbolize his power and rumors spread that he would replace the Emperor. Meanwhile, young lovers Mu Shun (Hiroshi Tamaki) and Ling Ju (Liu Yi-Fei) are taken from a prison camp to a hidden tomb, where they spend five cruel years together, training as assassins for a secret mission. In the year 220 BC astronomical signs predict dramatic change. As a result, Cao's son Cao Pi (Yau Sam-Chi) and Cao's followers urge Cao to become the new Emperor - but unknown opposing forces plot against him.",
      release_date: "2012-09-26",
      vote_count: 37,
      adult: false,
      backdrop_path: "/wGIypSW7q4k98sBHsKXGuH5akxf.jpg",
      id: 136701,
      genre_ids: [18, 36],
      title: "The Assassins",
      original_language: "zh",
      original_title: "铜雀台",
      popularity: 4.457,
      character: "Ling Ju / Diao Chan",
      credit_id: "52fe4c1bc3a368484e1a774d",
      order: 1,
    },
    {
      poster_path: "/keINQqFnbovPS5NuYFhgeE1i5Rv.jpg",
      video: false,
      vote_average: 6.8,
      overview:
        "The four constables Emotionless, Iron Hands , Life Snatcher and ColdBlood are specially skilled in their own individual super powers. When the four constables of the Divine Constabulary investigate a murder in the suburbs, they unexpectedly stumble on clues to the murder of Emotionless's family 15 years ago.",
      release_date: "2013-11-21",
      vote_count: 35,
      adult: false,
      backdrop_path: "/4HJm8s2s0Br18IqtuQLxnnES2St.jpg",
      id: 251749,
      genre_ids: [28],
      title: "The Four 2",
      original_language: "zh",
      original_title: "四大名捕2",
      popularity: 7.904,
      character: "Emotionless",
      credit_id: "52fe4e229251416c91127a41",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/dUyTuhjC3tnSeygWeU9CrByS461.jpg",
      genre_ids: [28, 80],
      original_language: "zh",
      original_title: "四大名捕大结局",
      poster_path: "/zXeEs2NCtw6IGoHxkxcsYQskpRK.jpg",
      video: false,
      id: 299738,
      vote_count: 43,
      overview:
        "The reputation of the Four constables survives, but since Emotionless’s departure, there have been changes at the Divine Constabulary. The four Coldblood, Iron Hands, Life Snatcher, rescue Zhuge Zhengwo from An Yunshan’s mountain fortress, then with the Emperor and Di armies, they attack. But An Yunshan absorbs their power, which means the constables and their allies now face their most lethal opponent yet, a nearly invincible kung fu master who won’t stop until he has absolute power...",
      release_date: "2014-08-21",
      vote_average: 5.8,
      title: "The Four 3",
      popularity: 7.881,
      character: "Emotionless",
      credit_id: "5451c0080e0a263a0a005984",
      order: 1,
    },
    {
      id: 400385,
      video: false,
      vote_count: 4,
      vote_average: 5.3,
      title: "Night Peacock",
      release_date: "2016-05-20",
      original_language: "zh",
      original_title: "夜孔雀",
      genre_ids: [18, 10749],
      backdrop_path: "/vpjpvJuvoOSPzw1dOyh00E61exT.jpg",
      adult: false,
      overview:
        "Liu Yifei plays Elso, a reputed French flutist who travels from Paris to Chengdu. Her life is compared to the one of a night peacock, an eternal conflict between life and death, love and time. A night peacock, by Fabre’s definition, is a moth with the life goal of finding their soul mate.",
      poster_path: "/2j28Cx1xOmu1Mi6mN6MLcGuSV1r.jpg",
      popularity: 0.954,
      character: "Elso",
      credit_id: "574e9cdfc3a36820e500073d",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/Jr9f5beevy3V6QtVcwnLxCdCGN.jpg",
      genre_ids: [35, 18, 10749],
      id: 405755,
      original_language: "zh",
      original_title: "致青春·原来你还在这里",
      overview:
        "A wealthy young man pursues a young woman of modest means, but circumstances often separate them as the years pass.",
      poster_path: "/6sFFzLjItKXdOQrSufN2Yh7cafd.jpg",
      release_date: "2016-07-08",
      title: "So Young 2: Never Gone",
      video: false,
      vote_average: 6.8,
      vote_count: 28,
      popularity: 3.788,
      character: "Su Yun Jin",
      credit_id: "57fc78ce9251411871003b48",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [10749],
      id: 825833,
      original_language: "zh",
      original_title: "阿宝的故事",
      overview: "",
      poster_path: "/fYjLyR94VdNDra40Iurbr0lTNgs.jpg",
      release_date: "2006-01-26",
      title: "阿宝的故事",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 0.6,
      character: "茜茜",
      credit_id: "6090d675f29d66006e07ff7b",
      order: 1,
    },
    {
      backdrop_path: "/4rEzmJinx4scTyotI4XXqz91F9x.jpg",
      genre_ids: [18, 28],
      original_language: "zh",
      original_title: "鸿门宴",
      poster_path: "/q31bbuzcEjy6Kbxf4QRzPhejeMc.jpg",
      video: false,
      vote_average: 6.8,
      vote_count: 30,
      overview:
        "White Vengeance tells the story of two brothers contending for supremacy during the fall of the Qin Dynasty, which ruled Imperial China from 221 to 206 BC. As rebels rose, the nation fell into chaos. Liu Bang and Xiang Yu, became leaders of the rebellious army, and also became sworn brothers in battle.Xiang Yu and Liu Bang are close friends who both serve King Huai of Chu. King Huai uses a plot, saying that whoever can subvert the Qin kingdom in Guanzhong would be the Lord Qin, in order to benefit from the competition between Xiang Yu and Liu Bang. Xiang Yu is over-confident. He fights against the main force of Qin army, and entrusts Liu Bang with Yu Ji, the woman he loves.Liu Bang expresses his love to Yu Ji and takes the chance to invade Guanzhong first when most of Qin army is outside fighting against Xiang Yu’s army.",
      release_date: "2011-11-29",
      title: "White Vengeance",
      id: 81344,
      adult: false,
      popularity: 3.018,
      character: "Yu Ji",
      credit_id: "52fe480a9251416c9107e24d",
      order: 2,
    },
    {
      video: false,
      title: "Outcast",
      overview:
        "A mysterious warrior teams up with the daughter and son of a deposed Chinese Emperor to defeat their cruel Uncle, who seeks their deaths.",
      release_date: "2014-09-26",
      vote_count: 352,
      adult: false,
      backdrop_path: "/sETF4vyjb0FonUJVqgrkaPWqiIf.jpg",
      id: 289720,
      genre_ids: [28],
      vote_average: 5,
      original_language: "en",
      original_title: "Outcast",
      poster_path: "/efsgCTlofzIuysfokEp7hwQnUho.jpg",
      popularity: 27.703,
      character: "Lian",
      credit_id: "540314f9c3a368119c0001ff",
      order: 2,
    },
    {
      id: 365952,
      original_title: "第三种爱情",
      poster_path: "/8mN32ZuiSCVbH36BEvyEiYKapAa.jpg",
      video: false,
      vote_average: 6.7,
      overview:
        '"The Third Way of Love" tells the sad love story of Lin Qi Zheng, who is from a rich family, and Zhou Yu who is a smart and beautiful lawyer.',
      release_date: "2015-09-25",
      vote_count: 14,
      adult: false,
      backdrop_path: "/hKkX7TDTvtR8Rc7RNA0e0WNxYrN.jpg",
      title: "The Third Way of Love",
      genre_ids: [10749],
      original_language: "zh",
      popularity: 2.373,
      character: "Zhou Yu",
      credit_id: "5633410cc3a3681b610154ca",
      order: 2,
    },
    {
      id: 240089,
      video: false,
      vote_count: 2,
      vote_average: 5,
      title: "The Love Winner",
      release_date: "2004-03-28",
      original_language: "zh",
      original_title: "恋爱大赢家",
      genre_ids: [18, 10749],
      backdrop_path: null,
      adult: false,
      overview:
        "In seven days, a young man must learn how to fight from a master, because, for the girl he is in love with, he have to challenge the current grand title owner, whose father is rivaling the smuggling business of the young man's father.",
      poster_path: "/hckMCbiClflkmrL4bqXBA5yfIg7.jpg",
      popularity: 0.672,
      character: "Lily Kim",
      credit_id: "546f7a7792514112e7002ae0",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/rDIPVZq5TNkiILKhXvNoItDohfP.jpg",
      genre_ids: [],
      id: 514696,
      original_language: "en",
      original_title: "Inversion",
      overview:
        "A street-wise American con man teams with a young Chinese physicist as they race against the clock to save the earth from a terrifying loss of gravity.",
      poster_path: null,
      release_date: "",
      title: "Inversion",
      video: false,
      vote_average: 0,
      vote_count: 0,
      popularity: 0.876,
      character: "",
      credit_id: "5abb68bf0e0a2609db010434",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/xeFk9s7vwYuxflTEW6Umelzevkr.jpg",
      genre_ids: [28, 18, 80],
      id: 120143,
      original_language: "zh",
      original_title: "四大名捕",
      overview:
        "An undercover agent is assigned by his corrupt chief to infiltrate a rival department and sabotage their investigation of counterfeit currency. What he discovers is the counterfeiter's real plan. To overthrow the capital. Not by flooding it with funny money, but with an army of undead.",
      poster_path: "/pWegm8do0HoVyvA8QMCNg313VEW.jpg",
      release_date: "2012-07-12",
      title: "The Four",
      video: false,
      vote_average: 6.5,
      vote_count: 57,
      popularity: 6.282,
      character: "Shong Yayu (Emotionless) (as Liu Yi Fei)",
      credit_id: "5f0e9415162bc3003526a08a",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/aNKhC2nzGr3kAggKubJ56MbFOUc.jpg",
      title: "The Forbidden Kingdom",
      genre_ids: [28, 12, 14],
      original_language: "en",
      original_title: "The Forbidden Kingdom",
      poster_path: "/mkrwLBAFHwLnQF8qdhCH0VOQqff.jpg",
      video: false,
      vote_average: 6.6,
      vote_count: 1218,
      overview:
        "An American teenager who is obsessed with Hong Kong cinema and kung-fu classics makes an extraordinary discovery in a Chinatown pawnshop: the legendary stick weapon of the Chinese sage and warrior, the Monkey King. With the lost relic in hand, the teenager unexpectedly finds himself travelling back to ancient China to join a crew of warriors from martial arts lore on a dangerous quest to free the imprisoned Monkey King.",
      id: 1729,
      release_date: "2008-04-18",
      popularity: 26.599,
      character: "Golden Sparrow / Chinatown Girl",
      credit_id: "52fe4312c3a36847f80381a5",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35, 10749],
      id: 417114,
      original_language: "en",
      original_title: "那件瘋狂的小事叫愛情",
      overview:
        "I Love That Crazy Little Thing is a 2016 Chinese romantic comedy film directed by Snow Zou and starring William Chan, Tang Yixin and Jessica Jung.[2] It was released in China by EMP Distribution (Beijing) and Wanda Shengshi Film Distribution on August 12, 2016",
      poster_path: "/zyPmswyZD98Fd5b1x5O676QAmp3.jpg",
      release_date: "2016-11-03",
      title: "I Love That Crazy Little Thing",
      video: false,
      vote_average: 4.5,
      vote_count: 2,
      popularity: 0.659,
      character: "",
      credit_id: "5abbe1730e0a2609db018a25",
      order: 4,
    },
  ],
  crew: [],
  id: 122503,
};

export const genres = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Documentary",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10402: "Music",
  9648: "Mystery",
  10749: "Romance",
  878: "Science Fiction",
  10770: "TV Movie",
  53: "Thriller",
  10752: "War",
  37: "Western",
};

export const examplePerson = {
  adult: false,
  also_known_as: [
    "劉亦菲",
    "Liu Yi Fei",
    "Yi-Fei Liu",
    "Liu Yi-Fei",
    "Crystal Liu",
    "刘亦菲",
    "An Feng",
    "Liu Ximeizi",
    "刘茜美子",
    "安风",
    "유역비",
    "Γιφέι Λιου",
    "Lưu Diệc Phi",
    "류이페이",
  ],
  biography:
    "Liu Yifei ( born An Feng; August 25, 1987) is a popular Chinese-American actress, model and singer. She was born in China and moved to the United States when she was 11.",
  birthday: "1987-08-25",
  deathday: null,
  gender: 1,
  homepage: null,
  id: 122503,
  imdb_id: "nm1703577",
  known_for_department: "Acting",
  name: "Liu Yifei",
  place_of_birth: "Wuhan, Hubei, China",
  popularity: 7.764,
  profile_path: "/cL6JccAYqiZQEAIEFObEUC9LTt7.jpg",
};
